#!/usr/bin/env python3

import rospy
from onrobot_rg_control.msg import OnRobotRGInput


def printStatus(status):
    """ Prints the status string generated by the statusInterpreter. """

    rospy.loginfo(statusInterpreter(status))


def OnRobotRGStatusListener():
    """ Initializes the node and subscribe to the OnRobotRGInput topic. """

    rospy.init_node(
        'OnRobotRGStatusListener', anonymous=True, log_level=rospy.DEBUG)
    rospy.Subscriber("OnRobotRGInput", OnRobotRGInput, printStatus)
    rospy.spin()


def statusInterpreter(status):
    """ Generates a string according to the current status. """

    output = '\n-----\nOnRobot RG status interpreter\n-----\n'

    # gFOF
    output += 'gFOF = ' + str(status.gFOF) + ': '
    output += 'Current fingertip offset: ' + str(status.gFOF / 10.0) + ' mm\n'

    # gGWD
    output += 'gGWD = ' + str(status.gGWD) + ': '
    output += 'Current width between the gripper fingers (w/o offset): ' + \
              str(status.gGWD / 10.0) + ' mm\n'

    # gSTA
    output += 'gSTA = ' + str(status.gSTA) + ': '
    gSTA16bit = format(status.gSTA, '016b')
    output += '(gSTA (16 bit) = ' + gSTA16bit + '), Currtent states: '
    if int(gSTA16bit[-1]):
        output += ' A motion is ongoing so new commands are not accepted.'
    if int(gSTA16bit[-2]):
        output += ' An internal- or external grip is detected.'
    if int(gSTA16bit[-3]):
        output += ' Safety switch 1 is pushed.'
    if int(gSTA16bit[-4]):
        output += ' Safety circuit 1 is activated so the gripper cannot move.'
    if int(gSTA16bit[-5]):
        output += ' Safety switch 2 is pushed.'
    if int(gSTA16bit[-6]):
        output += ' Safety circuit 2 is activated so the gripper cannot move.'
    if int(gSTA16bit[-7]):
        output += ' Any of the safety switch is pushed.'

    # gWDF
    output += '\ngWDF = ' + str(status.gWDF) + ': '
    output += 'Current width between the gripper fingers (w offset): ' + \
              str(status.gWDF / 10.0) + ' mm\n'

    return output


if __name__ == '__main__':
    OnRobotRGStatusListener()
